name: Update YouTube Videos

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  update-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client

      - name: Run script to update videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python update_videos.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'suvojit213'
          git config --global user.email 'suvojitsengupta21@gmail.com'
          git add src/data/videos.json
          if ! git diff --staged --quiet; then
            git commit -m "Automated: Update YouTube videos"
            git push https://suvojit213:${{ secrets.PAT }}@github.com/suvojit213/bio_page.git HEAD:main
          fi